name: teguk_time
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # carousel_slider: 4.1.1
  http: ^0.13.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3
  provider: ^6.1.1
  intl: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/slide1.png
    - assets/images/slide2.png
    - assets/images/slide3.png
    - assets/images/image.png
